name: ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999


    steps:
    - name: sshx install
      run: sudo apt update && sudo apt install curl && curl -sSf https://sshx.io/get | sh
    - name: sshx start
      run: sshx
